Makefile
updated build info available after this fix
```
curl -s localhost:${port}/debug/vars | grep -i Build
"BuildGitRev": "4491ce5e2924cd84f5b3e4aec9c712c97e59dc98",
"BuildHost": "build-slave-vitess1604",
"BuildTimestamp": 1496877855,
"BuildUser": "jenkinsslave",
```
=> Fix bug in make file to add buildinfo the vitess binaries

go/cmd/automation_server/automation_server.go, go/cmd/l2vtgate/main.go, go/cmd/mysqlctld/mysqlctld.go, go/cmd/vtcombo/main.go, go/cmd/vtctl/vtctl.go, go/cmd/vtctld/main.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgateclienttest/main.go, go/cmd/vttablet/vttablet.go, go/cmd/vtworker/vtworker.go, go/vt/servenv/buildinfo.go
This PR expose some build informations like git hash, build time, go version/OS/architecture etc. via the stats API and the new CLI flag `version`. 
```
$ ./vtctl -version
Version: a78c18da1fbb913a6f630667028d4c9ab713e66a built on Tue Jun 13 05:41:49 PDT 2017 by jenkinsslave@build-slave-vitess1604 using go1.8.3 linux/amd64
```
=> Expose version number

go/vt/vtgate/plugin_mysql_server.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go
Revert #22 since the "correct" fix is to add an optional default autocommit mode to vtgate.
In the meantime just force all new mysql sessions to vtgate so they have autocommit enabled by default which fixes the problem.
=> Slack vtgate default autocommit hack

.travis.yml
* Set go_import_path so forks of the project can benefit from Travis CI. Without
this change there are some assumptions in the bootstrap [script](https://github.com/rafael/vitess/blob/master/dev.env#L24) and also in the
import of packages that won't be hold in a fork of the project and the tests
will break.
* [go_import_path](https://docs.travis-ci.com/user/languages/go/) feature from travis solves this problem.
=> Fix for travis ci

go/vt/mysqlctl/backup.go, go/vt/mysqlctl/mysql_daemon.go, test/tablet.py
* This should address this issue https://github.com/youtube/vitess/issues/2908
* This commit refreshes mysql config after a backup. In this case, if there were config changes after stopping the mysql daemon, restart after the backup will have these changes.
* Tested locally.
=> Refresh MySQL config after a backup

go/vt/servenv/grpc_server.go, go/vt/servenv/grpcutils/options.go, go/vt/vtgate/executor_dml_test.go, go/vt/vtgate/grpcvtgateconn/conn.go, go/vt/vtgate/vindexes/lookup_hash_test.go, go/vt/vtgate/vindexes/lookup_hash_unique_test.go, go/vt/vtgate/vindexes/lookup_internal.go, go/vt/vtgate/vindexes/lookup_test.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletserver/txlogz.go, go/vt/vttablet/tabletserver/txlogz_test.go
This branch contains an updated slack fork for vitess in a way that syncs us back with upstream/master and then applies three slack-specific patches that we still need to run with.
This PR is based off the `slack-new-master` branch. Once approved, I'll merge this PR into that branch, rename our existing master branch to`slack-old-master-20170821`, and force-push the merged `slack-new-master` as our new master branch.
To prepare the branch I looked through our history and found the earliest merge point.
From that I created two new tags:
* slack-vitess-081417r0-base (7b7c6e6): the base of our current fork, including previous slack-specific history
* slack-vitess-081417r0-upstream (a5a7253): upstream commit that we last synced.
The content of these two tags / commits are equivalent.
I then …
=> slack merge upstream 2017 08 21

go/sync2/consolidator.go, go/vt/servenv/grpc_server.go, go/vt/servenv/grpcutils/options.go, go/vt/vtgate/grpcvtgateconn/conn.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/tabletserver/txlogz.go, go/vt/vttablet/tabletserver/txlogz_test.go, go/vt/vttablet/tabletserver/txserializer/tx_serializer_test.go
Preparation branch for the next upstream sync.
The latest upstream commit is 24c74fc tagged with slack-vitess-08.31.2017r0-upstream.
I force pushed that commit to the `slack-new-master` branch.
This shows all the upstream changes that we are pulling in:
https://github.com/tinyspeck/vitess/compare/tinyspeck:slack-vitess-082117r0-upstream...tinyspeck:slack-vitess-08.31.2017r0-upstream
These are the slack-specific patches on top of that.
As in #34, this also includes:
e1a81a1 make grpc max message size options apply to the client as well
4031aaf redact out the /txlogz endpoint completely
I did not include this since it should now be covered by the actual upstream fixes for upsert (#3066):
88860e5 `insert ignore` hack for vindex lookup to be updated
I also added the following:
1d544c9 redact …
=> Slack upstream sync 08.31.2017

go/vt/servenv/buildinfo.go, tools/build_version_flags.sh
Tested:
```
akotian@slack-vtctld-dev-025a0a18c54fb9a57:~$ ./vtctld -version 
Version: 1849db4 (91) (Git branch 'HEAD') built on Thu Oct  5 12:32:03 PDT 2017 by jenkinsslave@build-slave-vitess1604 using go1.8.3 linux/amd64
```
```
{
"BuildGitBranch": "HEAD",
"BuildGitRev": "1849db4",
"BuildHost": "build-slave-vitess1604",
"BuildNumber": 91,
"BuildTimestamp": 1507231923,
"BuildUser": "jenkinsslave",
```
=> Expose BuildNumber as a metric

go/vt/binlog/grpcbinlogplayer/player.go
This one was missed in the original implementation.
It's used during filtered replication to make a grpc call from one tablet to the other.
=> add the StaticAuthDialOption to the binlogplayer grpc client

go/cmd/automation_server/automation_server.go, go/cmd/l2vtgate/main.go, go/cmd/mysqlctld/mysqlctld.go, go/cmd/vtcombo/main.go, go/cmd/vtctl/vtctl.go, go/cmd/vtctld/main.go, go/cmd/vtexplain/vtexplain.go, go/cmd/vtgate/vtgate.go, go/cmd/vtgateclienttest/main.go, go/cmd/vttablet/vttablet.go, go/vt/servenv/servenv.go, go/vt/srvtopo/resilient_server.go, go/vt/srvtopo/resilient_server_test.go
Cherry-pick fixes for #3573 and #3574.
=> Slack cherry pick 2018 01 23

go/vt/mysqlproxy/mysqlproxy.go
This accidentally got left in and it exposes full queries in the debug log. So let's not do that.
=> remove debugging printf

go/vt/vttablet/tabletmanager/orchestrator.go
Fix bug found in dev: Orchestrator returns an empty length active-recovery response when it has no history of recovery on that cluster. An empty length active-recovery response is normal, and should mean that Orchestrator is not actively recovering that instance.
=> Fix bug found in dev with empty length active-recovery response.

go/mysql/conn_params.go, go/vt/dbconfigs/dbconfigs.go, go/vt/servenv/grpc_server.go
* Cherry picked https://github.com/vitessio/vitess/pull/4121 and https://github.com/vitessio/vitess/pull/4130 to slack upstream sync.
=> Slack sync upstream 2018.08.09r2

go/vt/callinfo/plugin_grpc.go, go/vt/callinfo/plugin_mysql.go, go/vt/vtgate/plugin_mysql_server.go
* Cherry picks gRPC caller info improvements from: 
* https://github.com/vitessio/vitess/pull/4151
* https://github.com/vitessio/vitess/pull/4153
=> add a callinfo implementation for the mysql server protocol

go/vt/vtcombo/tablet_map.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/tmclient/rpc_client_api.go, go/vt/wrangler/reparent.go
Reverts `FLUSH BINARY LOGS` changes so we use the implementation that landed in master.
=> Revert flush binary logs

go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/topo/consultopo/server.go
* Cherry picks commit to fix issue with backups.
* Cherry picks commit to make consul missing tokens warning less verbose.
=> Slack vitess 2018 10 29.r1

go/vt/discovery/tablet_stats_cache.go, go/vt/vtctl/vtctl.go, go/vt/vtgate/gateway/discoverygateway_test.go
The following PR cherry picks to changes from upstream that will unblock next steps of multi cell steps: 
* Fixes bug in aggregate stats that prevents cross cell routing within the same region: https://github.com/vitessio/vitess/pull/4459
* Enhances `ListAllTablets` command to work in all cells: https://github.com/vitessio/vitess/pull/4460
=> Slack sync upstream 2018 12 17.r1

go/sqltypes/result.go, go/sqltypes/result_test.go
Patch to handle this case while we move towards a permanent fix upstream.
=> Patch sqltypes.MakeRowTrusted to lean on field count

go/vt/dbconfigs/dbconfigs.go
[This commit](https://github.com/vitessio/vitess/pull/4814) seems to have broken the way tablets process their `-db-config-*-charset` parameters, resulting in `utf8mb4` not being honored. There's an [issue](https://github.com/vitessio/vitess/issues/4870) opened upstream that is tracking this but reverting here so we can move forward with our deploy.
Ran the testcase outlined in the upstream issue and it works with this change.
=> [dbconfigs] Revert tablet breaking change from upstream 

bootstrap.sh, go/streamlog/streamlog.go, go/vt/vtgate/engine/delete.go, go/vt/vtgate/engine/insert.go, go/vt/vtgate/engine/update.go, go/vt/vtgate/logstats.go, go/vt/vtgate/logstats_test.go, go/vt/vtgate/planbuilder/delete.go, go/vt/vtgate/planbuilder/insert.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/select.go, go/vt/vtgate/planbuilder/testdata/dml_cases.txt, go/vt/vtgate/planbuilder/update.go, go/vt/vtgate/querylogz_test.go, go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/querylogz_test.go, go/vt/vttablet/tabletserver/tabletenv/logstats.go, go/vt/vttablet/tabletserver/tabletenv/logstats_test.go, go/vt/vttablet/tabletserver/tabletserver.go, go/vt/vttablet/tabletserver/tx_engine.go, go/vt/vttablet/tabletserver/tx_engine_test.go, go/vt/vttablet/tabletserver/tx_executor.go, go/vt/vttablet/tabletserver/tx_pool.go, go/vt/vttablet/tabletserver/tx_pool_test.go
This forks our 2019-04-02 build and "cherry picks" in the following changes:
1. https://github.com/vitessio/vitess/pull/4824 &mdash; Respect timeouts in all statements
2. https://github.com/vitessio/vitess/pull/4827 &mdash; Correctly suppress begin...commit in auto-commit logs
3. https://github.com/vitessio/vitess/pull/4895 &mdash; Adds optional tag-based query logging
4. https://github.com/vitessio/vitess/pull/4891 &mdash; fix build due to broken dependency
I squashed commits 2 and 3 each into a single commit on this branch. Item 2 did not apply cleanly so I had to manually resolve merge conflicts.
Once this merge is approved we will reset our master branch to point here and tag the old master branch so that it's not lost should we need to recover that state:
```
git checkout …
```
=> Cherry pick changes into our build

go/mysql/server.go, go/mysql/server_test.go, go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go, go/vt/topo/consultopo/watch.go, go/vt/vtgate/gateway/discoverygateway.go, go/vt/wrangler/reparent.go, go/vt/wrangler/tablet.go, go/vt/wrangler/tablet_test.go
Adhoc deploy containing _just_ the following changes:
* commit https://github.com/vitessio/vitess/commit/2f0e6ae10f8d420cb227c735ea497186f22d7a64, PR https://github.com/vitessio/vitess/pull/5647 from planetscale/ds-delete-tablet-fake-master
deepthi adding support for safer DeleteTablet on old masters
* commit https://github.com/vitessio/vitess/commit/35a689b06984bcdb12a8f994db7f14fd52adb5d0, PR https://github.com/vitessio/vitess/pull/5673 from planetscale:consultopo-watch-heartbeat
makes consultopo watcher not remain stalled after network partition
* commit https://github.com/vitessio/vitess/commit/edb59bdb5fc6bb5a51be92f36b5ff4de50e998fa, PR https://github.com/vitessio/vitess/pull/5815 from tinyspeck/sp-limit-hc-by-keyspace
serry adding support for limiting topo healthchecks per keyspace …
=> Slack vitess 2020 03 11.r0

go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
* Cherry picks https://github.com/vitessio/vitess/pull/6040 to fix issue with handle other.
=> Adds supports to target DestinationKeyspaceID to handle other

go.mod, go.sum, go/vt/mysqlctl/xtrabackupengine.go
In attempting to deploy 5.0 we've run into two problems with backups:
1. Problem with traditional non-xtrabackup tablets on the new build, hitting ```use of closed network connection: cannot copy data: MultipartUpload: upload multipart failed.```
It looks like this is *maybe* is caused by the AWS SDK bump. Our hypothesis is that it might be [this problem](https://github.com/aws/aws-sdk-go/issues/2825#issuecomment-533641264) filed upstream in the new AWS SDK version.
2. On xtrabackup backed up tablets on the new build, we’re occasionally hitting this panic:
```Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, caught panic during Backup: bufio: writer returned negative count from Write```
Our hypothesis is that this is caused by an incorrect writer (or possibly a buggy …
=> Let's try reverting.

go/cmd/vttablet/vttablet.go, go/mysql/flavor_filepos.go, go/vt/vttablet/tabletmanager/action_agent.go, go/vt/vttablet/tabletmanager/init_tablet_test.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vdiff.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client_test.go, go/vt/vttablet/tabletserver/api.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/resultstreamer.go, go/vt/wrangler/migrater_env_test.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go
* Create a new vifl-master branch that is in sync with our master + vdiff ad-hoc changes. 
* This is the same as: https://github.com/tinyspeck/vitess/pull/144
=> This is a combination of 6 commits.

go/vt/vtctl/vtctl.go, go/vt/vtctld/vtctld.go, go/vt/wrangler/schema.go
* Cherry picks this PR: https://github.com/vitessio/vitess/pull/6216 
* This only needs to be deployed to vtctld.
=> Slack vitess 2020.06.02.r0

go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go, go/vt/vtgate/gateway/discoverygateway.go
This pulls in [vitessio#5815](https://github.com/vitessio/vitess/pull/5815) from upstream which limits healthchecks to keyspaces in a vtgate's `keyspaces_to_watch` flag.
=> [vifl, patch] Add vtgate health check limiting into vifl branch

go/vt/discovery/topology_watcher.go, go/vt/discovery/topology_watcher_test.go, go/vt/vtgate/gateway/discoverygateway.go
This pulls in [vitessio#5815](https://github.com/vitessio/vitess/pull/5815) from upstream which limits healthchecks to keyspaces in a vtgate's `keyspaces_to_watc` flag.
=> Pulls in vtgate health check limiting

go/vt/vtgate/engine/delete.go
This change that went out in 6.0 is causing problems for our one table with scatter deletes and a lookup vindex. Fix forward by cherry-picking in this fix.
=> Cherrypick keep deletevindexentries for scatter queries.

go/cmd/vttablet/vttablet.go, go/mysql/flavor_filepos.go, go/vt/vttablet/tabletmanager/action_agent.go, go/vt/vttablet/tabletmanager/init_tablet_test.go, go/vt/vttablet/tabletmanager/vreplication/controller.go, go/vt/vttablet/tabletmanager/vreplication/engine.go, go/vt/vttablet/tabletmanager/vreplication/engine_test.go, go/vt/vttablet/tabletmanager/vreplication/framework_test.go, go/vt/vttablet/tabletmanager/vreplication/vdiff.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client.go, go/vt/vttablet/tabletmanager/vreplication/vstreamer_client_test.go, go/vt/vttablet/tabletserver/api.go, go/vt/vttablet/tabletserver/vstreamer/engine.go, go/vt/vttablet/tabletserver/vstreamer/resultstreamer.go, go/vt/wrangler/testlib/migrate_served_from_test.go, go/vt/wrangler/testlib/migrate_served_types_test.go, go/vt/wrangler/traffic_switcher_env_test.go
Description
This branch syncs vifls branch with tinyspeck/master (Vitess 6.0).  Once we feel this is good and we merge it, I will force push this branch to vifl-master-two to vifl-master. Opening against our current master to make it easy to reason about. 
* Starts by applying https://github.com/tinyspeck/vitess/pull/158.
* Previously we also cherry picked https://github.com/tinyspeck/vitess/pull/159  and https://github.com/tinyspeck/vitess/pull/162, but they are already part of 6.0, so we no longer need to apply these changes.
=> Vifl slack vitess 2020.06.22.r7

go/vt/vtgate/vindexes/lookup.go, go/vt/vtgate/vindexes/lookup_unique_test.go, go/vt/worker/legacy_split_clone.go
Instead of setting up vreplication to filter by keyranges, let's set it up to replicate entire tables since we are going to be merging and we want all records in the destination. This should be a safe operation since we'll be validating source shards using out of band scripts. Also, throw in a hardcode of the `LookupUnique` vindex since we need it to [not be ignored by vtworkers](https://github.com/tinyspeck/vitess/blob/aa70055e985bc77692243218f3700f1dc773f240/go/vt/vtgate/vindexes/vschema.go#L673-L675).
- In `LegacySplitClone`, collect table names from source shards and construct `BinlogSource` accordingly
- hardcode `LookupUnique` cost
vtworkers build.
=> [VITESS-1055/VITESS-1057] LegacySplitClone: VReplicate entire tables instead of keyrange

go/vt/worker/legacy_split_clone.go
When testing this in dev, found that the vreplication request setup after the copy step of `LegacySplitClone` would include empty table names. This PR does the more defensive thing of filtering out empty table names and uniquifies them as well
- use a map to collect table names and turn into a slice when needed.
- existing unit tests continue to pass/fail
- rolling out to dev to mess around with
=> [legacy_split_clone] Filter out empty table names and uniquify tables for vreplication request

go/vt/vtctl/endtoend/get_schema_test.go, go/vt/vtctl/vtctl.go
Add option to GetSchema to only send the row count and data length over the wire
Signed-off-by: Andrew Mason <amason@slack-corp.com>
=> Add option to GetSchema to only send the row count and data length over the wire

go/vt/worker/legacy_row_splitter.go, go/vt/worker/legacy_split_clone.go
Tracks how many rows were dropped and which keys got dropped.
Testing -- in dev, validated in success and dropped row cases. Didn't validate the logic around bad rows but it's less pressing since we're currently not planning on continuing in those cases.
We can come back and build out additional tooling there if we want to build some kind bad-key blessing. This change also puts structure in place for that by plumbing the table around.
=> [vmerge] Add stats to the post merge report

go/vt/wrangler/reparent.go
This takes the core of the change from https://github.com/vitessio/vitess/pull/7486 and backports it into 8.0.
=> Backport some panic protection during ERS

go/vt/discovery/healthcheck.go, go/vt/srvtopo/keyspace_filtering_server.go, go/vt/vtgate/discoverygateway.go, go/vt/vtgate/vcursor_impl.go, go/vt/vtgate/vtgate.go
This checks if a vtgate is currently filtering keyspaces before requesting the TopoServer. This is necessary because a TopoServer can't be accessed in those cases as the filtered Topo in those cases could make it unsafe to make writes since all reads would be returning a subset of the actual topo data.
The only use of the requested topoServer that I found was in the DDL handling path and was introduced in https://github.com/vitessio/vitess/pull/6547.
This is deployed on dev but should get testing (endtoend or unit, unclear on best path atm) before going upstream.
=> Fix bug in vtgate when running with keyspace filtering

go/vt/vtctl/endtoend/get_schema_test.go, go/vt/vtctl/vtctl.go
There were merge conflicts here, would appreciate extra eyes.
Two items of note
:one: the following diff no longer seemed relevant given that the grpc interface had been evolved to support sizes only as a first class flag
```
+       if *tableSizesOnly {
+               sizeTds := make([]*tabletmanagerdatapb.TableDefinition, len(sd.TableDefinitions))
+               for i, td := range sd.TableDefinitions {
+                       sizeTds[i] = &tabletmanagerdatapb.TableDefinition{
+                               Name:       td.Name,
+                               Type:       td.Type,
+                               RowCount:   td.RowCount,
+                               DataLength: td.DataLength,
+                       }
+               }
+
+               sd.TableDefinitions = sizeTds …
```
=> Vitess v8 VTctld custom branch + sizes-only

go/cmd/vttablet/vttablet.go, go/vt/mysqlctl/metadata_tables.go, go/vt/vttablet/tabletmanager/tm_init.go, go/vt/vttablet/tabletmanager/tm_init_test.go, go/vt/vttablet/tabletmanager/tm_state.go, go/vt/vttablet/tabletmanager/tm_state_test.go
This cherry-picks a squashed version of https://github.com/vitessio/vitess/pull/8107 into our master branch
Signed-off-by: Andrew Mason <amason@slack-corp.com>
Defer populating metadata to handle different queryservice states
If we're enabling the queryservice, wait until afterwards to populate
the metadata. On the other hand, if we're disabling the queryservice,
then populate the metadata just before shutting down the queryservice.
Signed-off-by: Andrew Mason <amason@slack-corp.com>
Update testTM mysqldaemon to support local_metadata queries
Signed-off-by: Andrew Mason <amason@slack-corp.com>
Add missing `updateLocked` call on tablettype change in test
Signed-off-by: Andrew Mason <amason@slack-corp.com>
Track whether tm_state is opening, and try to respect the `init_populate_metadata` …
=> [tm_state] updateLocked should re-populate local metadata tables to reflect promotion rule changes

go/cmd/vtctldclient/internal/command/backups.go, go/vt/mysqlctl/azblobbackupstorage/azblob.go, go/vt/mysqlctl/backup.go, go/vt/mysqlctl/backupengine.go, go/vt/mysqlctl/backupstorage/interface.go, go/vt/mysqlctl/builtinbackupengine.go, go/vt/mysqlctl/cephbackupstorage/ceph.go, go/vt/mysqlctl/filebackupstorage/file.go, go/vt/mysqlctl/gcsbackupstorage/gcs.go, go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/mysqlctl/xtrabackupengine.go, go/vt/vtctl/grpcvtctldserver/server.go
This brings in #8308 , via:
```
git cherry-pick 7e6673c^..38e842e 
```
which is broadly just "all the commits in the branch". If we're comfortable with this, I'll squash-n-merge this into the r13 branch, and then we'll merge that result.
=> add backup status to vtctld 9.0 branch
