go/vt/vtgate/plugin_mysql_server.go
Cherry-pick a fix for the panic on vtgate.
=> don't try to roll back on a nonexistent session

go/mysqlconn/conn.go, go/mysqlconn/server.go
Add logging to indicate where slow connections and hangups are coming from.
=> Connection log remote endpoint

go/vt/vttablet/tabletmanager/rpc_external_reparent.go, go/vt/vttest/environment.go, go/vt/vttest/local_cluster.go
=> Slack sync upstream 2017 07 06

go/mysql/conn.go, go/mysql/server.go, go/mysql/server_test.go, go/vt/vtgate/plugin_mysql_server.go
Slack-specific version of #2981
=> Mysql conn timings and warnings

go/vt/vtgate/engine/route.go, go/vt/vtgate/gateway/discoverygateway_test.go, go/vt/vtgate/gateway/shard_error.go, go/vt/vtgate/resolver_test.go, go/vt/vtgate/scatter_conn_test.go, go/vt/vttablet/tabletserver/txlogz.go, go/vt/vttablet/tabletserver/txlogz_test.go
a few fixes and changes for our environment that aren't ready for upstream.
=> Slack hacks and patches

go/vt/vttablet/tabletserver/query_executor.go, go/vt/vttablet/tabletserver/query_executor_test.go, vendor/vendor.json
to fix the `select ... for update` error
=> fixing `disallow outside transactions` of select for update

examples/local/mysql_auth_server_static_creds.json, examples/local/vtgate-up.sh, go/mysql/auth_server.go, go/mysql/auth_server_none.go, go/mysql/auth_server_static.go, go/mysql/auth_server_static_test.go, go/mysql/handshake_test.go, go/mysql/ldapauthserver/auth_server_ldap.go, go/mysql/server.go, go/mysql/server_test.go, go/vt/vtgate/plugin_mysql_server.go
* Same as: https://github.com/youtube/vitess/pull/3115, but for our master branch. Would like to merge here first and get it deployed 🚀.
* So far, I've tested this in a local cluster and one vtgate box our dev environment.
=>  Slack/myslq server host check

go/vt/vtctld/api.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_test.go
Fix show vitess_shards and the vtctld UI when there is an invalid keyspace.
=> Slack 2017 09 28 patches

go/cmd/vttablet/vttablet.go, go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/vttablet/tabletmanager/action_agent.go
Pull in #3349 and #3346 from upstream.
=> Slack sync upstream 2017 11 03

examples/local/grpc_static_auth.json, examples/local/grpc_static_client_auth.json, examples/local/vtctld-up.sh, examples/local/vtgate-up.sh, examples/local/vttablet-up.sh, go/vt/grpcclient/client.go, go/vt/grpcclient/client_auth_static.go, go/vt/servenv/grpc_auth_plugin.go, go/vt/servenv/grpc_server.go, go/vt/servenv/grpc_server_auth_static.go, go/vt/throttler/grpcthrottlerclient/grpcthrottlerclient.go, go/vt/vtctl/grpcvtctlclient/client.go, go/vt/vtctl/grpcvtctlclient/client_test.go, go/vt/vtgate/gatewaytest/suite.go, go/vt/vtgate/grpcvtgateconn/conn.go, go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/grpctabletconn/conn_test.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/worker/grpcvtworkerclient/client.go, go/vt/worker/grpcvtworkerclient/client_test.go, test/local_example.sh
* This commit adds an interface to implement auth plugin
in Vitess grpc server
* It also implements an static plugin that allows client/server
to authentic using basic auth.
=>  Add grpc auth interface and static implementation

examples/local/vtctld-up.sh, examples/local/vtgate-up.sh, examples/local/vttablet-up.sh, go/vt/grpcclient/client_auth_static.go, go/vt/servenv/grpc_server.go, go/vt/servenv/grpc_server_auth_static.go, go/vt/throttler/grpcthrottlerclient/grpcthrottlerclient.go, go/vt/vtctl/grpcvtctlclient/client.go, go/vt/vtctl/grpcvtctlclient/client_test.go, go/vt/vtgate/grpcvtgateconn/conn.go, go/vt/vtgate/grpcvtgateconn/conn_rpc_test.go, go/vt/vttablet/grpctabletconn/conn.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/tabletconntest/tabletconntest.go, go/vt/worker/grpcvtworkerclient/client.go, go/vt/worker/grpcvtworkerclient/client_test.go
=> Improvements per code review

data/test/vtgate/dml_cases.txt, go/vt/vtexplain/vtexplain_vtgate.go, go/vt/vtgate/engine/primitive.go, go/vt/vtgate/executor.go, go/vt/vtgate/executor_framework_test.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/executor_test.go, go/vt/vtgate/planbuilder/builder.go, go/vt/vtgate/planbuilder/dml.go, go/vt/vtgate/planbuilder/insert.go, go/vt/vtgate/planbuilder/plan_test.go, go/vt/vtgate/vtgate.go
The following is a proposal to have a one round trip commit from vtgate to vtablet when is safe to do so. 
* Validate that it's safe to set tabletAutocommitAllowed for all unsharded queries. 
Unit tests for planning and executor.
=> One round trip commit POC

go/vt/vtgate/executor.go
* Added fix for show vindexes. https://github.com/youtube/vitess/pull/3618
=> Slack sync upstream  2018-02-07 (2)

vendor/vendor.json
Add the `promhttp` & updated `prometheus` packages to the vendor.json file. 
I'd like to cut a fresh Docker bootstrap image with these new dependencies so that the CI tests for my followup Prometheus PR can run successfully.
=> Add the `promhttp` & updated `prometheus` packages to the vendor.json file. 

go/vt/vtgate/vtgate.go
Includes https://github.com/vitessio/vitess/pull/3780 into the build.
=> Slack vitess 2018.03.26r1

go/vt/discovery/healthcheck.go
Update our fork again to pull in the logging update to my previous changes.
=> Slack sync upstream 2018 05 08

go/vt/grpcclient/client.go, java/client/pom.xml, java/example/pom.xml, java/grpc-client/pom.xml, java/hadoop/pom.xml, java/jdbc/pom.xml, java/jdbc/src/main/java/io/vitess/util/Constants.java, java/pom.xml
Sync branch with upstream.
* One more sync to add gRPC client knobs.
=> Slack sync upstream 2018.05.18r1

go/vt/mysqlctl/s3backupstorage/s3.go, go/vt/vtcombo/tablet_map.go, go/vt/vttablet/faketmclient/fake_client.go, go/vt/vttablet/grpctmclient/client.go, go/vt/vttablet/tmclient/rpc_client_api.go, go/vt/wrangler/reparent.go, vendor/vendor.json
* Cherry picks: https://github.com/vitessio/vitess/pull/4163
=> Slack flush binlogs reparent 2018.08.29r1

go/vt/mysqlctl/s3backupstorage/s3.go, vendor/vendor.json
This reverts commit 105c0a40ec7ae9f6915c2f835666b658ef0da74c.
=> Revert "Try backups with buffer io"

go/vt/mysqlctl/backup.go, go/vt/mysqlctl/s3backupstorage/s3.go, vendor/vendor.json
* Cherry picks this PR: https://github.com/vitessio/vitess/pull/4221, so we can improve backups speed.
=> Initial import of change to parallelize backup compresion

bootstrap.sh
Cherrypicks a commit to update the `golint` path in `bootstrap.sh`
=> Cherry-pick: Fix golint install in bootstrap.sh

go/vt/vttablet/tabletserver/tabletserver.go
- Cherry picks: https://github.com/vitessio/vitess/pull/4761
=> Fix potential nil pointer error

go/vt/mysqlctl/xtrabackupengine.go
This reverts commit dd7954491becb9c0ce3cf54bd9967c86d80ba2cc.
=> Reverts the xtrabackup commit

go/vt/wrangler/reparent.go
OP https://github.com/vitessio/vitess/pull/7523
This basically protects from trying to catch up on replication on hosts that are likely not replicating.
I believe this to be a faithful recreation, a clean cherry-pick was not possible because I don't have the `EmergencyReparenter`refactor.
=> Backport vitessio#7523 into 8.0

go/test/endtoend/vtgate/system_schema_test.go, go/vt/vtgate/engine/route.go, go/vt/vtgate/engine/route_test.go, go/vt/vtgate/evalengine/expressions.go, go/vt/vtgate/executor_select_test.go, go/vt/vtgate/planbuilder/route.go, go/vt/vtgate/planbuilder/system_tables.go, go/vt/vtgate/planbuilder/testdata/filter_cases.txt, go/vt/vtgate/planbuilder/testdata/from_cases.txt, go/vt/vtgate/planbuilder/testdata/select_cases.txt, go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt, go/vt/vtgate/vindexes/vschema.go, go/vt/vtgate/vindexes/vschema_test.go, go/vt/vtgate/vtgate_test.go
Brings the following PR's to our build:
* https://github.com/vitessio/vitess/pull/7430
* https://github.com/vitessio/vitess/pull/8087
This should fix the regressions we saw when querying information schema tables.
=> Slack vitess 9 2021.03.16r5

go/vt/vtctl/grpcvtctldserver/server.go, go/vt/vtctl/vtctl.go, go/vt/vtctl/workflow/server.go, go/vt/wrangler/vdiff.go, go/vt/wrangler/vdiff_test.go
* Cherry picks https://github.com/vitessio/vitess/pull/8266 in to our 9.0 release 
* Cherry picks https://github.com/vitessio/vitess/pull/8079/files
=> slack-vitess-9-2021.06.07r7.vtctld

go/vt/binlog/binlogplayer/binlog_player.go, go/vt/vttablet/tabletmanager/vreplication/stats.go, go/vt/vttablet/tabletmanager/vreplication/vplayer.go
This brings https://github.com/vitessio/vitess/pull/8306 into our deploy
=> slack vitess 9 2021 05.24r9

go/vt/vtctl/grpcvtctldclient/client.go
This cherry-picks 3370c06fe9f19ed1df885a4998ce76122a177512
Signed-off-by: Andrew Mason <amason@slack-corp.com>
=> slack vitess 9 2021.06.07r15.vtctld

go/vt/vttablet/customrule/filecustomrule/filecustomrule.go, go/vt/vttablet/tabletserver/rules/rules_test.go
This adds https://github.com/vitessio/vitess/pull/8233 to our 10.0 deploy.
- 
Components that this PR will affect:
=> slack vitess v10.0.2 r1
